[build]
  base = "/client/live-poll-frontend"
  publish = ".next"
  command = "npm ci --include=dev && npm run build"

[cache]
  directories = ["node_modules"]

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_LOGLEVEL = "error"
  NEXT_PUBLIC_SOCKET_URL = "https://api.netlify.com/functions/server"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"

[functions.server]
  path = "../server/index.js"
  memory_size = 1024
  timeout = 10
  environment = [
    "NODE_ENV",
    "PORT"
  ]

[redirects]
  from = "/*"
  to = "/index.html"
  status = 200
