[build]
  base = "/"
  publish = "/client/live-poll-frontend/.next"
  command = "cd client/live-poll-frontend && npm run build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[functions.server]
  path = "server/index.js"
  memory_size = 1024
  timeout = 10
  environment = [
    "NODE_ENV",
    "PORT"
  ]
