[build]
  base = "client/live-poll-frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[functions.server]
  path = "server/index.js"
  memory_size = 1024
  timeout = 10
  environment = [
    "NODE_ENV",
    "PORT"
  ]
